#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Feb 11 15:17:12 2022

@author: ppxmg2
"""

import numpy as np
import matplotlib.pyplot as plt
import halomodel_optimised as hm
import os

# Range of PBH masses to consider
#m_pbhs = 10**np.arange(-1, 3.1, 1)
m_pbhs = 10**np.arange(1, 2.1, 1)

# Uppermost values of the event duration to plot, in years
upper = (800 * (1 + np.log10(m_pbhs))) / 365.25

# Range of numbers of PBHs per cluster to consider
#n_cls = 10**np.arange(3, 7.1, 1.)
n_cls = 10**np.arange(5, 5.1, 1.)

# Number of realisations for each PBH mass and cluster size
n_realisations = 3

"""Calculate the number of expected events, given a sample of cluster distances and speeds"""
for k, m_pbh in enumerate(m_pbhs):
    
    # import relevant comparison curve for the event duration distribution
    filepath = f'{os.getcwd()}' + '/data_files/event_duration_dist_step=0.50_mpbh={:.2f}'.format(np.log10(m_pbh)) + '.txt'
    t_smooth, dgamma_smooth = np.loadtxt(filepath, delimiter = ',')
    
    print(np.trapz(dgamma_smooth, np.array(t_smooth)/365.25))
    
    for n_cl in n_cls:
        
        setup = hm.Halomodel(m_pbh=m_pbh, n_cl=n_cl)
        
        for i in range(n_realisations):
            filepath = f'{os.getcwd()}' + '/simulated_data_constraints/N_cl/{0:.2f}'.format(np.log10(n_cl)) + '/M_PBH/{0:.2f}/'.format(np.log10(m_pbh)) + str(i)
            d_L = np.loadtxt(filepath + '_dL.txt', delimiter=',')
            v = np.loadtxt(filepath + '_v.txt', delimiter=',')
            
            t_hat = 2 * setup.einstein_radius(d_L) / v
            gamma_c = setup.event_rate(d_L, v)
            
            bin_spacing = upper[k] / np.sqrt(len(t_hat))
                        
            plt.figure()
            plt.hist(t_hat, weights = np.array(gamma_c) / bin_spacing, bins = np.arange(0, upper[k]+bin_spacing/2, bin_spacing))
            plt.plot(np.array(t_smooth) / 365.25, dgamma_smooth, color='k')
            plt.xlabel('$\hat{t}$ / yr')
            plt.ylabel(r'$\frac{\mathrm{d}\Gamma}{\mathrm{d} \hat{t}}$ / $\mathrm{yr}^{-2}$')
            plt.xlim(0, upper[k])
            plt.ylim(0, max(dgamma_smooth) * 1.5)
            plt.title('$N_\mathrm{cl}$' + '$ = 10^{:.0f}$'.format(np.log10(n_cl)) + ', $M_\mathrm{PBH} $' + '$= 10^{:.0f} M_\odot$'.format(np.log10(m_pbh)))          

